[package]
name = "yournal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive", "string"] }
cliclack = "0.3.5"
edit = "0.1.5"
paris = "1.5.15"
